//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resourses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AddBuildingResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AddBuildingResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resourses.AddBuildingResources", typeof(AddBuildingResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SE2.
        /// </summary>
        public static string AbbeyWood {
            get {
                return ResourceManager.GetString("AbbeyWood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W3, W4.
        /// </summary>
        public static string Acton {
            get {
                return ResourceManager.GetString("Acton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR0.
        /// </summary>
        public static string Addington {
            get {
                return ResourceManager.GetString("Addington", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IG2.
        /// </summary>
        public static string AldboroughHatch {
            get {
                return ResourceManager.GetString("AldboroughHatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EC3.
        /// </summary>
        public static string Aldgate {
            get {
                return ResourceManager.GetString("Aldgate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WC2.
        /// </summary>
        public static string Aldwych {
            get {
                return ResourceManager.GetString("Aldwych", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SE20.
        /// </summary>
        public static string Anerley {
            get {
                return ResourceManager.GetString("Anerley", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TN16.
        /// </summary>
        public static string Aperfield {
            get {
                return ResourceManager.GetString("Aperfield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N19.
        /// </summary>
        public static string Archway {
            get {
                return ResourceManager.GetString("Archway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RM11.
        /// </summary>
        public static string ArdleighGreen {
            get {
                return ResourceManager.GetString("ArdleighGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EN5, NW7.
        /// </summary>
        public static string Arkley {
            get {
                return ResourceManager.GetString("Arkley", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N11, N14.
        /// </summary>
        public static string ArnosGrove {
            get {
                return ResourceManager.GetString("ArnosGrove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SW12.
        /// </summary>
        public static string Balham {
            get {
                return ResourceManager.GetString("Balham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SE1.
        /// </summary>
        public static string Bankside {
            get {
                return ResourceManager.GetString("Bankside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HA0.
        /// </summary>
        public static string PostcodeAlpertoAlperton {
            get {
                return ResourceManager.GetString("PostcodeAlpertoAlperton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live.
        /// </summary>
        public static string PropertyStatus1 {
            get {
                return ResourceManager.GetString("PropertyStatus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not live.
        /// </summary>
        public static string PropertyStatus2 {
            get {
                return ResourceManager.GetString("PropertyStatus2", resourceCulture);
            }
        }
    }
}
