using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Resourses
{
    public static class MappingStaticClass
    {
        public static string Home = "Home";
        public static string HomeIndex = "Index";
        public static string HomeAboutUs = "AboutUs";
        public static string HomeBuying = "Buying";
        public static string HomeContactUs = "ContactUs";
        public static string HomeLandlords = "Landlords";
        public static string HomeRenting = "Renting";
        public static string HomeSelling = "Selling";
        public static string LeftNavPanel = "_LeftNavPanel";
        public static string ChangePart1 = "<%Message%>";
        public static string ChangePart2 = "<%Name%>";
        public static string ChangePart3 = "<%PhoneNumber%>";
        public static string ChangePart4 = "<%TitleAnswer%>";
        public static string ChangePart5 = "<%ConnectTime%>";
        public static string CredentialsMail = "CredentialsMail";
        public static string CredentialsPassword = "CredentialsPassword";
        public static string SmtpHost = "smtpHost";
        public static string SmtpPort = "smtpPort";
        public static string HtmlTemplate = "HtmlTemplate";
        public static string AdminFirstName = "AdminFirstName";
        public static string AdminSecondName = "AdminSecondName";
        public static string SellingSidebar = "_Sidebar";
        public static string SellingSelling = "Selling";
        public static string SellingRenting = "Renting";
        public static string SellingHome = "Home";
        public static string PageSize = "pageSize";
        public static string PropertyList = "PropertyList";
        public static string MailSuccess = "MailSuccess";
        public static string MailError = "MailError";
        public static string PropertyDetails = "PropertyDetails";
        public static string VertNavigation = "_VertNavigation";
        public static string pageInPaging = "pageInPaging";
        public static string pageSize = "pageSize";
        public static string sessionSalePage = "pageSale";
        public static string sessionRentPage = "pageRent";
        public static string propertyListView = "_PropertyList";
        public static string RentingRenting = "Renting";
        public static string CMSMenuPartial = "CMSMenuPartial";
        public static string Admin = "Admin";
        public static string AddNewBuilding = "AddNewBuilding";
        public static string Selling = "Selling";
        public static string Renting = "Renting";
        public static string LogOn = "LogOn";
        public static string Account = "Account";
        public static string CMSPostsPartial = "CMSPostsPartial";
        public static string CMS = "CMS";
        public static string ForSale = "ForSale";
        public static string ForRent = "ForRent";
        public static string News = "News";
        public static string ChangePassword = "ChangePassword";
        public static string LogOut = "LogOut";
        public static string image = "image";
        public static string txtPath0 = "txtPath0";
        public static string disabled = "disabled";
        public static string file0 = "file0";
        public static string blah = "blah";
        public static string txtPath = "txtPath";
        public static string Saver = "Saver";
        public static string deleter = "deleter";
        public static string NewsDelete = "NewsDelete";
        public static string Descriptions = "Descriptions";
        public static string Images = "Images";
        public static string Plan2D = "Plan2D";
        public static string Plan3D = "Plan3D";
        public static string _Images = "_Images";
        public static string _Descriptions = "_Descriptions";
        public static string CMSDetails = "CMSDetails";
        public static string _AddNewBuildingContent = "_AddNewBuildingContent";
        public static string i1to10 = "1-10";
        public static string i11to20 = "11-20";
        public static string i21to30 = "21-30";
        public static string EPC = "EPC";
        public static string AjaxUpload = "AjaxUpload";
        public static string UploadForm = "UploadForm";
        public static string CreateCMSType = "CreateCMSType";
        public static string _CMSPostsPartial = "_CMSPostsPartial";
        public static string _CMSMenuPartial = "_CMSMenuPartial";
        public static string oper = "oper";
        public static string del = "del";
        public static string Id = "Id";
        public static string PropertyStatus = "PropertyStatus";
        public static string photo = "photo";
        public static string jpg = "jpg";
        public static string jpeg = "jpeg";
        public static string png = "png";
        public static string Password = "Password";
        public static string NewPassword = "NewPassword";
        public static string PropertStatus = "PropertyStatus";
        public static string pathToThumbnailFolder = "pathToThumbnailFolder";
        public static string pathToCloseUpFolder = "pathToCloseUpFolder";
        public static string pathToOriginalFolder = "pathToOriginalFolder";
    }
}