//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resourses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WebSiteResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebSiteResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resourses.WebSiteResources", typeof(WebSiteResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AdminMail.
        /// </summary>
        public static string _adminMail {
            get {
                return ResourceManager.GetString("_adminMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContactUs.
        /// </summary>
        public static string _contactUs {
            get {
                return ResourceManager.GetString("_contactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write your phone number. \r\nExample: 020-8558-1147.
        /// </summary>
        public static string _enterYourPhoneNumber {
            get {
                return ResourceManager.GetString("_enterYourPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your name.
        /// </summary>
        public static string _pleaseEnterYourName {
            get {
                return ResourceManager.GetString("_pleaseEnterYourName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide a property on your website, PropertySpring, and all data feeds (Rightmove,
        ///					                etc)..
        /// </summary>
        public static string AddBuildingText1 {
            get {
                return ResourceManager.GetString("AddBuildingText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/B/ Changes may take up to 24 hours to take effect on Rightmove..
        /// </summary>
        public static string AddBuildingText2 {
            get {
                return ResourceManager.GetString("AddBuildingText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Item.
        /// </summary>
        public static string AddNewItem {
            get {
                return ResourceManager.GetString("AddNewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bathrooms.
        /// </summary>
        public static string Bathrooms {
            get {
                return ResourceManager.GetString("Bathrooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bedrooms.
        /// </summary>
        public static string Bedrooms {
            get {
                return ResourceManager.GetString("Bedrooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string btnContactUs {
            get {
                return ResourceManager.GetString("btnContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Details.
        /// </summary>
        public static string btnPropertyDetailsFullDetails {
            get {
                return ResourceManager.GetString("btnPropertyDetailsFullDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building record successfully removed.
        /// </summary>
        public static string Buildingrecordsuccessfullyremoved {
            get {
                return ResourceManager.GetString("Buildingrecordsuccessfullyremoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMS.
        /// </summary>
        public static string CMS {
            get {
                return ResourceManager.GetString("CMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anytime.
        /// </summary>
        public static string ContactAnytime {
            get {
                return ResourceManager.GetString("ContactAnytime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiday AM.
        /// </summary>
        public static string ContactFidayAM {
            get {
                return ResourceManager.GetString("ContactFidayAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiday PM.
        /// </summary>
        public static string ContactFidayPM {
            get {
                return ResourceManager.GetString("ContactFidayPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string ContactMessageHeader {
            get {
                return ResourceManager.GetString("ContactMessageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday AM.
        /// </summary>
        public static string ContactMondayAM {
            get {
                return ResourceManager.GetString("ContactMondayAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday PM.
        /// </summary>
        public static string ContactMondayPM {
            get {
                return ResourceManager.GetString("ContactMondayPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxx-xxxx-xxxx.
        /// </summary>
        public static string ContactPhoneNumber {
            get {
                return ResourceManager.GetString("ContactPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday AM.
        /// </summary>
        public static string ContactSaturdayAM {
            get {
                return ResourceManager.GetString("ContactSaturdayAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday PM.
        /// </summary>
        public static string ContactSaturdayPM {
            get {
                return ResourceManager.GetString("ContactSaturdayPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday AM.
        /// </summary>
        public static string ContactThursdayAM {
            get {
                return ResourceManager.GetString("ContactThursdayAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday PM.
        /// </summary>
        public static string ContactThursdayPM {
            get {
                return ResourceManager.GetString("ContactThursdayPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string ContactTitle {
            get {
                return ResourceManager.GetString("ContactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint.
        /// </summary>
        public static string ContactTitle1 {
            get {
                return ResourceManager.GetString("ContactTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer.
        /// </summary>
        public static string ContactTitle2 {
            get {
                return ResourceManager.GetString("ContactTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another Question.
        /// </summary>
        public static string ContactTitle3 {
            get {
                return ResourceManager.GetString("ContactTitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday AM.
        /// </summary>
        public static string ContactWednesdayAM {
            get {
                return ResourceManager.GetString("ContactWednesdayAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday PM.
        /// </summary>
        public static string ContactWednesdayPM {
            get {
                return ResourceManager.GetString("ContactWednesdayPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday AM.
        /// </summary>
        public static string ContatTuesdayAM {
            get {
                return ResourceManager.GetString("ContatTuesdayAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday PM.
        /// </summary>
        public static string ContatTuesdayPM {
            get {
                return ResourceManager.GetString("ContatTuesdayPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New CMS Type.
        /// </summary>
        public static string CreateNewCMSType {
            get {
                return ResourceManager.GetString("CreateNewCMSType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password is wrong.
        /// </summary>
        public static string CurrentPasswordError {
            get {
                return ResourceManager.GetString("CurrentPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Image.
        /// </summary>
        public static string DeleteImage {
            get {
                return ResourceManager.GetString("DeleteImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descriptions.
        /// </summary>
        public static string Descriptions {
            get {
                return ResourceManager.GetString("Descriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string DetailsNo {
            get {
                return ResourceManager.GetString("DetailsNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string DetailsYes {
            get {
                return ResourceManager.GetString("DetailsYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPC.
        /// </summary>
        public static string EPC {
            get {
                return ResourceManager.GetString("EPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ooups. Some error occured..
        /// </summary>
        public static string Error1 {
            get {
                return ResourceManager.GetString("Error1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 404 Page will be there some day.
        /// </summary>
        public static string Error404 {
            get {
                return ResourceManager.GetString("Error404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find a Property.
        /// </summary>
        public static string FindaProperty {
            get {
                return ResourceManager.GetString("FindaProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Rent.
        /// </summary>
        public static string ForRent {
            get {
                return ResourceManager.GetString("ForRent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Sale.
        /// </summary>
        public static string ForSale {
            get {
                return ResourceManager.GetString("ForSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Furnished status.
        /// </summary>
        public static string FurnishedUnfurnished {
            get {
                return ResourceManager.GetString("FurnishedUnfurnished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garden.
        /// </summary>
        public static string Garden {
            get {
                return ResourceManager.GetString("Garden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect username or password.
        /// </summary>
        public static string Incorrectusernameorpassword {
            get {
                return ResourceManager.GetString("Incorrectusernameorpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input new CMS Type Name.
        /// </summary>
        public static string InputnewCMSTypeName {
            get {
                return ResourceManager.GetString("InputnewCMSTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid type. Only the following types (jpg, jpeg, png) are supported..
        /// </summary>
        public static string InvalidType {
            get {
                return ResourceManager.GetString("InvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of RentEstate.
        /// </summary>
        public static string ListofRentEstate {
            get {
                return ResourceManager.GetString("ListofRentEstate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Sale Estate.
        /// </summary>
        public static string ListofSaleEstate {
            get {
                return ResourceManager.GetString("ListofSaleEstate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Living rooms.
        /// </summary>
        public static string Livingrooms {
            get {
                return ResourceManager.GetString("Livingrooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to London.
        /// </summary>
        public static string London {
            get {
                return ResourceManager.GetString("London", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long Description.
        /// </summary>
        public static string LongDescription {
            get {
                return ResourceManager.GetString("LongDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Information.
        /// </summary>
        public static string MainInformation {
            get {
                return ResourceManager.GetString("MainInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Photo.
        /// </summary>
        public static string MainPhoto {
            get {
                return ResourceManager.GetString("MainPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password is required field.
        /// </summary>
        public static string NewPasswordIsRequired {
            get {
                return ResourceManager.GetString("NewPasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password and Confirm password fields are not matched..
        /// </summary>
        public static string NewPasswordNotMatched {
            get {
                return ResourceManager.GetString("NewPasswordNotMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New title.
        /// </summary>
        public static string Newtitle {
            get {
                return ResourceManager.GetString("Newtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoImage.png.
        /// </summary>
        public static string NoImage {
            get {
                return ResourceManager.GetString("NoImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Title.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parking.
        /// </summary>
        public static string Parking {
            get {
                return ResourceManager.GetString("Parking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\..\Content\img\main.
        /// </summary>
        public static string pathToCloseUpFolder {
            get {
                return ResourceManager.GetString("pathToCloseUpFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\..\Content\img\details.
        /// </summary>
        public static string pathToOriginalFolder {
            get {
                return ResourceManager.GetString("pathToOriginalFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\..\Content\img\min.
        /// </summary>
        public static string pathToThumbnailFolder {
            get {
                return ResourceManager.GetString("pathToThumbnailFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo:.
        /// </summary>
        public static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The size of the file should not exceed 10 MB.
        /// </summary>
        public static string PhotoSize {
            get {
                return ResourceManager.GetString("PhotoSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string PLAboutUs {
            get {
                return ResourceManager.GetString("PLAboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2D Plan.
        /// </summary>
        public static string Plan2D {
            get {
                return ResourceManager.GetString("Plan2D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3D Plan.
        /// </summary>
        public static string Plan3D {
            get {
                return ResourceManager.GetString("Plan3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buying.
        /// </summary>
        public static string PLBuying {
            get {
                return ResourceManager.GetString("PLBuying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string PLContactUs {
            get {
                return ResourceManager.GetString("PLContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please log in to access the administrative area:.
        /// </summary>
        public static string Pleaselogintoaccesstheadministrativearea {
            get {
                return ResourceManager.GetString("Pleaselogintoaccesstheadministrativearea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Gallery.
        /// </summary>
        public static string PLGallery {
            get {
                return ResourceManager.GetString("PLGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string PLHome {
            get {
                return ResourceManager.GetString("PLHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Independent Estate &amp; Letting Agents | Property Management Services | Call 020 8558 1147.
        /// </summary>
        public static string PLIntro {
            get {
                return ResourceManager.GetString("PLIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landlords.
        /// </summary>
        public static string PLLandlords {
            get {
                return ResourceManager.GetString("PLLandlords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _LeftNavPanel.
        /// </summary>
        public static string PLLeftNavPanel {
            get {
                return ResourceManager.GetString("PLLeftNavPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent agreed.
        /// </summary>
        public static string PLRentAgreed {
            get {
                return ResourceManager.GetString("PLRentAgreed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renting.
        /// </summary>
        public static string PLRenting {
            get {
                return ResourceManager.GetString("PLRenting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale agreed.
        /// </summary>
        public static string PLSaleAgreed {
            get {
                return ResourceManager.GetString("PLSaleAgreed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selling.
        /// </summary>
        public static string PLSelling {
            get {
                return ResourceManager.GetString("PLSelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tranding Place.
        /// </summary>
        public static string PLTrandingPlace {
            get {
                return ResourceManager.GetString("PLTrandingPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postcode.
        /// </summary>
        public static string Postcode {
            get {
                return ResourceManager.GetString("Postcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price: £.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties For Rent.
        /// </summary>
        public static string PropertiesForRent {
            get {
                return ResourceManager.GetString("PropertiesForRent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties For Sale.
        /// </summary>
        public static string PropertiesForSale {
            get {
                return ResourceManager.GetString("PropertiesForSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties Menu.
        /// </summary>
        public static string PropertiesMenu {
            get {
                return ResourceManager.GetString("PropertiesMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whilst every care is taken these particulars are intended as a general guide. All measurements are subject to a margin of error. Trading Places have not tested any of the appliances, services of connections and therefore cannot verify that they are in working order of fir for the purpose. This includes heating systems. All photographs and floor plans are for guidance purposes only and some photographs mat have been taken using a wide angle lens. Fixtures and
        ///									fittings are only included subject to a [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PropertyDetailsStuff {
            get {
                return ResourceManager.GetString("PropertyDetailsStuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property status.
        /// </summary>
        public static string Propertystatus {
            get {
                return ResourceManager.GetString("Propertystatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register With Us.
        /// </summary>
        public static string RegisterWithUs {
            get {
                return ResourceManager.GetString("RegisterWithUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale&apos;s Corner.
        /// </summary>
        public static string SalesCorner {
            get {
                return ResourceManager.GetString("SalesCorner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Description.
        /// </summary>
        public static string ShortDescription {
            get {
                return ResourceManager.GetString("ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shower.
        /// </summary>
        public static string Shower {
            get {
                return ResourceManager.GetString("Shower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some error occured. Reload page, please..
        /// </summary>
        public static string SomeError {
            get {
                return ResourceManager.GetString("SomeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry.
        /// </summary>
        public static string Sorry {
            get {
                return ResourceManager.GetString("Sorry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry. Some error occured. Cant create new item..
        /// </summary>
        public static string SorrySomeerroroccuredCantcreatenewitem {
            get {
                return ResourceManager.GetString("SorrySomeerroroccuredCantcreatenewitem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source for image.
        /// </summary>
        public static string Sourceforimage {
            get {
                return ResourceManager.GetString("Sourceforimage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source for new image.
        /// </summary>
        public static string Sourcefornewimage {
            get {
                return ResourceManager.GetString("Sourcefornewimage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSTC.
        /// </summary>
        public static string SSTC {
            get {
                return ResourceManager.GetString("SSTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Image.
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenure.
        /// </summary>
        public static string Tenure {
            get {
                return ResourceManager.GetString("Tenure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Buy.
        /// </summary>
        public static string text2Buy {
            get {
                return ResourceManager.GetString("text2Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find a Property.
        /// </summary>
        public static string text2Find {
            get {
                return ResourceManager.GetString("text2Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking to Sell?.
        /// </summary>
        public static string text2Looking {
            get {
                return ResourceManager.GetString("text2Looking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim.
        /// </summary>
        public static string text2Lorem {
            get {
                return ResourceManager.GetString("text2Lorem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read More.
        /// </summary>
        public static string text2Read {
            get {
                return ResourceManager.GetString("text2Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register With Us.
        /// </summary>
        public static string text2Register {
            get {
                return ResourceManager.GetString("text2Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Rent.
        /// </summary>
        public static string text2Rent {
            get {
                return ResourceManager.GetString("text2Rent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services for Landlords.
        /// </summary>
        public static string text2ServicesLandlords {
            get {
                return ResourceManager.GetString("text2ServicesLandlords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim.
        /// </summary>
        public static string text3Lorem {
            get {
                return ResourceManager.GetString("text3Lorem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read More.
        /// </summary>
        public static string text3Read {
            get {
                return ResourceManager.GetString("text3Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request a Valuation.
        /// </summary>
        public static string text3Request {
            get {
                return ResourceManager.GetString("text3Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim.
        /// </summary>
        public static string text4Lorem {
            get {
                return ResourceManager.GetString("text4Lorem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request a Valuation.
        /// </summary>
        public static string text4Request {
            get {
                return ResourceManager.GetString("text4Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 46 Church Lane.
        /// </summary>
        public static string textAdr1 {
            get {
                return ResourceManager.GetString("textAdr1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leytonstone, London.
        /// </summary>
        public static string textAdr2 {
            get {
                return ResourceManager.GetString("textAdr2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best time to contact you.
        /// </summary>
        public static string textBest {
            get {
                return ResourceManager.GetString("textBest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you considering selling, buying, letting or renting? We offer professional property services designed to meet your needs... Experience the difference, call us now on 020 8558 1147..
        /// </summary>
        public static string textCall {
            get {
                return ResourceManager.GetString("textCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        public static string textContactus {
            get {
                return ResourceManager.GetString("textContactus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E11 1HE.
        /// </summary>
        public static string textE111HE {
            get {
                return ResourceManager.GetString("textE111HE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string textEmail {
            get {
                return ResourceManager.GetString("textEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax:.
        /// </summary>
        public static string textFax {
            get {
                return ResourceManager.GetString("textFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 020 8556 6665.
        /// </summary>
        public static string textFax020 {
            get {
                return ResourceManager.GetString("textFax020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find a Property.
        /// </summary>
        public static string textFindAProperty {
            get {
                return ResourceManager.GetString("textFindAProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to info@tradingplacesproperty.com.
        /// </summary>
        public static string textInfo {
            get {
                return ResourceManager.GetString("textInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Lorem ipsum dolor sit amet, consectetuer.
        /// </summary>
        public static string textLorem {
            get {
                return ResourceManager.GetString("textLorem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Lorem ipsum dolor sit amet, consectetuer.
        /// </summary>
        public static string textLorem1 {
            get {
                return ResourceManager.GetString("textLorem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory field.
        /// </summary>
        public static string textMandatory {
            get {
                return ResourceManager.GetString("textMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string textName {
            get {
                return ResourceManager.GetString("textName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string textPhone {
            get {
                return ResourceManager.GetString("textPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register With Us.
        /// </summary>
        public static string textRegister {
            get {
                return ResourceManager.GetString("textRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tel:.
        /// </summary>
        public static string textTel {
            get {
                return ResourceManager.GetString("textTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 020 8558 1147.
        /// </summary>
        public static string textTel020 {
            get {
                return ResourceManager.GetString("textTel020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Buy.
        /// </summary>
        public static string textToBuy {
            get {
                return ResourceManager.GetString("textToBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Rent.
        /// </summary>
        public static string textToRent {
            get {
                return ResourceManager.GetString("textToRent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This cms type have not some posts..
        /// </summary>
        public static string ThisCmsTypehavenotsomeposts {
            get {
                return ResourceManager.GetString("ThisCmsTypehavenotsomeposts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Buy.
        /// </summary>
        public static string ToBuy {
            get {
                return ResourceManager.GetString("ToBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Rent.
        /// </summary>
        public static string ToRent {
            get {
                return ResourceManager.GetString("ToRent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type your message.
        /// </summary>
        public static string TypeYourMessage {
            get {
                return ResourceManager.GetString("TypeYourMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View on Street View.
        /// </summary>
        public static string VOSV {
            get {
                return ResourceManager.GetString("VOSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write content here. You can attach some html styles, pictures and other..
        /// </summary>
        public static string WriteContentHere {
            get {
                return ResourceManager.GetString("WriteContentHere", resourceCulture);
            }
        }
    }
}
